#pragma once

// Generated by tools/balance/monster_levels_client.py from the live database - do not edit by hand.
// The levels of the monsters on the server (the reset ladder); the client data has the original levels.

namespace GameLogic::Monsters
{
    struct MonsterLevel
    {
        int Number;
        int Level;
    };

    inline constexpr MonsterLevel MonsterLevels[] =
    {
        { 0, 6 }, // Bull Fighter
        { 1, 9 }, // Hound
        { 2, 4 }, // Budge Dragon
        { 3, 2 }, // Spider
        { 4, 12 }, // Elite Bull Fighter
        { 5, 38 }, // Hell Hound
        { 6, 14 }, // Lich
        { 7, 17 }, // Giant
        { 8, 82 }, // Poison Bull
        { 9, 78 }, // Thunder Lich
        { 10, 84 }, // Dark Knight
        { 11, 32 }, // Ghost
        { 12, 25 }, // Larva
        { 13, 40 }, // Hell Spider
        { 14, 19 }, // Skeleton Warrior
        { 15, 34 }, // Skeleton Archer
        { 16, 42 }, // Elite Skeleton
        { 17, 28 }, // Cyclops
        { 18, 90 }, // Gorgon
        { 19, 30 }, // Yeti
        { 20, 36 }, // Elite Yeti
        { 21, 26 }, // Assassin
        { 22, 22 }, // Ice Monster
        { 23, 24 }, // Hommerd
        { 24, 20 }, // Worm
        { 25, 52 }, // Ice Queen
        { 26, 3 }, // Goblin
        { 27, 5 }, // Chain Scorpion
        { 28, 10 }, // Beetle Monster
        { 29, 13 }, // Hunter
        { 30, 15 }, // Forest Monster
        { 31, 16 }, // Agon
        { 32, 18 }, // Stone Golem
        { 33, 8 }, // Elite Goblin
        { 34, 94 }, // Cursed Wizard
        { 35, 130 }, // Death Gorgon
        { 36, 70 }, // Shadow
        { 37, 112 }, // Devil
        { 38, 130 }, // Balrog
        { 39, 83 }, // Poison Shadow
        { 40, 121 }, // Death Knight
        { 41, 103 }, // Death Cow
        { 43, 15 }, // Golden Budge Dragon
        { 44, 47 }, // Red Dragon
        { 45, 50 }, // Bahamut
        { 46, 60 }, // Vepar
        { 47, 70 }, // Valkyrie
        { 48, 117 }, // Lizard King
        { 49, 117 }, // Hydra
        { 50, 74 }, // Sea Worm
        { 51, 90 }, // Great Bahamut
        { 52, 103 }, // Silver Valkyrie
        { 53, 53 }, // Golden Titan
        { 54, 46 }, // Golden Soldier
        { 57, 140 }, // Iron Wheel
        { 58, 145 }, // Tantallos
        { 59, 150 }, // Zaikan
        { 60, 135 }, // Bloody Wolf
        { 61, 150 }, // Beam Knight
        { 62, 130 }, // Mutant
        { 63, 150 }, // Death Beam Knight
        { 64, 70 }, // Orc Archer
        { 65, 74 }, // Elite Orc
        { 66, 86 }, // Cursed King
        { 67, 77 }, // Metal Balrog
        { 69, 150 }, // Alquamos
        { 70, 158 }, // Queen Rainer
        { 71, 154 }, // Mega Crust
        { 72, 168 }, // Phantom Knight
        { 73, 162 }, // Drakan
        { 74, 164 }, // Alpha Crust
        { 75, 169 }, // Great Drakan
        { 76, 106 }, // Dark Phoenix Shield
        { 77, 170 }, // Dark Phoenix
        { 78, 20 }, // Golden Goblin
        { 79, 80 }, // Golden Dragon
        { 80, 83 }, // Golden Lizard King
        { 81, 61 }, // Golden Vepar
        { 82, 90 }, // Golden Tantallos
        { 83, 77 }, // Golden Wheel
        { 84, 56 }, // Chief Skeleton Warrior 1
        { 85, 61 }, // Chief Skeleton Archer 1
        { 86, 66 }, // Dark Skull Soldier 1
        { 87, 70 }, // Giant Ogre 1
        { 88, 74 }, // Red Skeleton Knight 1
        { 89, 79 }, // Magic Skeleton 1
        { 90, 64 }, // Chief Skeleton Warrior 2
        { 91, 69 }, // Chief Skeleton Archer 2
        { 92, 75 }, // Dark Skull Soldier 2
        { 93, 79 }, // Giant Ogre 2
        { 94, 82 }, // Red Skeleton Knight 2
        { 95, 88 }, // Magic Skeleton 2
        { 96, 70 }, // Chief Skeleton Warrior 3
        { 97, 75 }, // Chief Skeleton Archer 3
        { 98, 80 }, // Dark Skull Soldier 3
        { 99, 85 }, // Giant Ogre 3
        { 111, 87 }, // Red Skeleton Knight 3
        { 112, 90 }, // Magic Skeleton 3
        { 113, 76 }, // Chief Skeleton Warrior 4
        { 114, 81 }, // Chief Skeleton Archer 4
        { 115, 86 }, // Dark Skull Soldier 4
        { 116, 90 }, // Giant Ogre 4
        { 117, 94 }, // Red Skeleton Knight 4
        { 118, 99 }, // Magic Skeleton 4
        { 119, 85 }, // Chief Skeleton Warrior 5
        { 120, 87 }, // Chief Skeleton Archer 5
        { 121, 90 }, // Dark Skull Soldier 5
        { 122, 93 }, // Giant Ogre 5
        { 123, 98 }, // Red Skeleton Knight 5
        { 124, 102 }, // Magic Skeleton 5
        { 125, 110 }, // Chief Skeleton Warrior 6
        { 126, 112 }, // Chief Skeleton Archer 6
        { 127, 118 }, // Dark Skull Soldier 6
        { 128, 120 }, // Giant Ogre 6
        { 129, 127 }, // Red Skeleton Knight 6
        { 130, 135 }, // Magic Skeleton 6
        { 135, 87 }, // White Wizard
        { 136, 70 }, // Destructive Ogre Soldier
        { 137, 74 }, // Destructive Ogre Archer
        { 138, 105 }, // Chief Skeleton Warrior 7
        { 139, 106 }, // Chief Skeleton Archer 7
        { 140, 110 }, // Dark Skull Soldier 7
        { 141, 112 }, // Giant Ogre 7
        { 142, 119 }, // Red Skeleton Knight 7
        { 143, 125 }, // Magic Skeleton 7
        { 144, 24 }, // Death Angel 1
        { 145, 33 }, // Death Centurion 1
        { 146, 21 }, // Blood Soldier 1
        { 147, 17 }, // Aegis 1
        { 148, 19 }, // Rogue Centurion 1
        { 149, 28 }, // Necron 1
        { 150, 52 }, // Bali
        { 151, 58 }, // Soldier
        { 160, 40 }, // Schriker 1
        { 161, 52 }, // Illusion of Kundun 1
        { 162, 30 }, // Chaos Castle 1
        { 163, 32 }, // Chaos Castle 2
        { 164, 40 }, // Chaos Castle 3
        { 165, 45 }, // Chaos Castle 4
        { 166, 54 }, // Chaos Castle 5
        { 167, 60 }, // Chaos Castle 6
        { 168, 65 }, // Chaos Castle 7
        { 169, 68 }, // Chaos Castle 8
        { 170, 70 }, // Chaos Castle 9
        { 171, 75 }, // Chaos Castle 10
        { 172, 76 }, // Chaos Castle 11
        { 173, 80 }, // Chaos Castle 12
        { 174, 76 }, // Death Angel 2
        { 175, 86 }, // Death Centurion 2
        { 176, 74 }, // Blood Soldier 2
        { 177, 70 }, // Aegis 2
        { 178, 72 }, // Rogue Centurion 2
        { 179, 80 }, // Necron 2
        { 180, 88 }, // Schriker 2
        { 181, 90 }, // Illusion of Kundun 2
        { 182, 123 }, // Death Angel 3
        { 183, 128 }, // Death Centurion 3
        { 184, 121 }, // Blood Soldier 3
        { 185, 117 }, // Aegis 3
        { 186, 119 }, // Rogue Centurion 3
        { 187, 126 }, // Necron 3
        { 188, 130 }, // Schriker 3
        { 189, 130 }, // Illusion of Kundun 3
        { 190, 155 }, // Death Angel 4
        { 191, 158 }, // Death Centurion 4
        { 192, 153 }, // Blood Soldier 4
        { 193, 150 }, // Aegis 4
        { 194, 152 }, // Rogue Centurion 4
        { 195, 157 }, // Necron 4
        { 196, 160 }, // Schriker 4
        { 197, 160 }, // Illusion of Kundun 4
        { 204, 2 }, // Wolf Status
        { 205, 2 }, // Wolf Altar1
        { 206, 2 }, // Wolf Altar2
        { 207, 2 }, // Wolf Altar3
        { 208, 2 }, // Wolf Altar4
        { 209, 2 }, // Wolf Altar5
        { 260, 178 }, // Death Angel 5
        { 261, 192 }, // Death Centurion 5
        { 262, 176 }, // Blood Soldier 5
        { 263, 170 }, // Aegis 5
        { 264, 172 }, // Rogue Centurion 5
        { 265, 184 }, // Necron 5
        { 266, 202 }, // Schriker 5
        { 267, 220 }, // Illusion of Kundun 5
        { 268, 287 }, // Death Angel 6
        { 269, 303 }, // Death Centurion 6
        { 270, 281 }, // Blood Soldier 6
        { 271, 270 }, // Aegis 6
        { 272, 276 }, // Rogue Centurion 6
        { 273, 298 }, // Necron 6
        { 274, 314 }, // Schriker 6
        { 275, 371 }, // Illusion of Kundun 7
        { 290, 156 }, // Lizard Warrior
        { 291, 170 }, // Fire Golem
        { 292, 166 }, // Queen Bee
        { 293, 160 }, // Poison Golem
        { 294, 152 }, // Axe Warrior
        { 295, 170 }, // Erohim
        { 304, 159 }, // Witch Queen
        { 305, 160 }, // Blue Golem
        { 306, 153 }, // Death Rider
        { 307, 147 }, // Forest Orc
        { 308, 140 }, // Death Tree
        { 309, 160 }, // Hell Maine
        { 310, 186 }, // Hammer Scout
        { 311, 188 }, // Lance Scout
        { 312, 190 }, // Bow Scout
        { 313, 210 }, // Werewolf
        { 314, 216 }, // Scout(Hero)
        { 315, 218 }, // Werewolf(Hero)
        { 316, 220 }, // Balram
        { 317, 219 }, // Soram
        { 331, 356 }, // Aegis 7
        { 332, 359 }, // Rogue Centurion 7
        { 333, 361 }, // Blood Soldier 7
        { 334, 364 }, // Death Angel 7
        { 335, 366 }, // Necron 7
        { 336, 368 }, // Death Centurion 7
        { 337, 371 }, // Schriker 7
        { 338, 320 }, // Illusion of Kundun 6
        { 350, 196 }, // Berserker
        { 351, 160 }, // Splinter Wolf
        { 352, 170 }, // Iron Rider
        { 353, 174 }, // Satyros
        { 354, 180 }, // Blade Hunter
        { 355, 182 }, // Kentauros
        { 356, 219 }, // Gigantis
        { 357, 200 }, // Genocider
        { 358, 400 }, // Persona
        { 359, 400 }, // Twin Tale
        { 360, 400 }, // Dreadfear
        { 361, 145 }, // Nightmare
        { 362, 130 }, // Maya (Hand Left)
        { 363, 130 }, // Maya (Hand Right)
        { 364, 140 }, // Maya
        { 409, 190 }, // Balram (Trainee Soldier)
        { 410, 190 }, // Death Spirit (Trainee Soldier)
        { 411, 190 }, // Soram (Trainee Soldier)
        { 412, 190 }, // Dark Elf (Trainee Soldier)
        { 418, 4 }, // Strange Rabbit
        { 419, 13 }, // Hideous Rabbit
        { 420, 19 }, // Hideous Rabbit
        { 421, 24 }, // Werewolf
        { 422, 30 }, // Cursed Lich
        { 423, 36 }, // Totem Golem
        { 424, 43 }, // Grizzly
        { 425, 48 }, // Captain Grizzly
        { 426, 111 }, // Chaos Castle 13
        { 427, 114 }, // Chaos Castle 14
        { 428, 114 }, // Chief Skeleton Warrior 8
        { 429, 117 }, // Chief Skeleton Archer 8
        { 430, 125 }, // Dark Skull Soldier 8
        { 431, 129 }, // Giant Ogre 8
        { 432, 132 }, // Red Skeleton Knight 8
        { 433, 140 }, // Magic Skeleton 8
        { 434, 98 }, // Gigantis
        { 435, 100 }, // Berserk
        { 436, 134 }, // Balram (Trainee)
        { 437, 134 }, // Soram (Trainee)
        { 438, 118 }, // Persona
        { 439, 119 }, // Dreadfear
        { 440, 135 }, // Dark_Elf
        { 441, 400 }, // Sapi-Unus
        { 442, 400 }, // Sapi-Duo
        { 443, 400 }, // Sapi-Tres
        { 444, 400 }, // Shadow Pawn
        { 445, 400 }, // Shadow Knight
        { 446, 400 }, // Shadow Look
        { 447, 400 }, // Thunder Napin
        { 448, 400 }, // Ghost Napin
        { 449, 400 }, // Blaze Napin
        { 454, 342 }, // Ice Walker
        { 455, 356 }, // Giant Mammoth
        { 456, 347 }, // Ice Giant
        { 457, 351 }, // Coolutin
        { 458, 356 }, // Iron Knight
        { 459, 400 }, // Selupan
        { 460, 378 }, // Spider Eggs 1
        { 461, 378 }, // Spider Eggs 2
        { 462, 378 }, // Spider Eggs 3
        { 480, 400 }, // Zombie Fighter
        { 481, 400 }, // Zombie Fighter
        { 482, 400 }, // Resurrected Gladiator
        { 483, 400 }, // Resurrected Gladiator
        { 484, 400 }, // Ash Slaughterer
        { 485, 400 }, // Ash Slaughterer
        { 486, 400 }, // Blood Assassin
        { 487, 400 }, // Cruel Blood Assassin
        { 488, 400 }, // Cruel Blood Assassin
        { 489, 400 }, // Burning Lava Giant
        { 490, 400 }, // Ruthless Lava Giant
        { 491, 400 }, // Ruthless Lava Giant
        { 504, 138 }, // Gayion The Gladiator
        { 505, 140 }, // Jerry
        { 506, 146 }, // Raymond
        { 507, 142 }, // Lucas
        { 508, 145 }, // Fred
        { 509, 143 }, // Hammerize
        { 510, 144 }, // Dual Berserker
        { 511, 141 }, // Devil Lord
        { 512, 134 }, // Quarter Master
        { 513, 118 }, // Combat Instructor
        { 514, 135 }, // Aticle's Head
        { 515, 134 }, // Dark Ghost
        { 516, 119 }, // Banshee
        { 517, 140 }, // Head Mounter
        { 518, 118 }, // Defender
        { 519, 115 }, // Forsaker
        { 520, 113 }, // Ocelot the Lord
        { 521, 120 }, // Eric the Guard
        { 524, 2 }, // Evil Gate
        { 525, 2 }, // Lion Gate
        { 526, 2 }, // Statue
        { 527, 2 }, // Star Gate
        { 528, 2 }, // Rush Gate
        { 549, 220 }, // Bloody Orc
        { 550, 237 }, // Bloody Death Rider
        { 551, 253 }, // Bloody Golem
        { 552, 270 }, // Bloody Witch Queen
        { 553, 320 }, // Berserker Warrior
        { 554, 332 }, // Kentauros Warrior
        { 555, 337 }, // Gigantis Warrior
        { 556, 342 }, // Genocider Warrior
        { 557, 400 }, // Sapi Queen
        { 558, 400 }, // Ice Napin
        { 559, 400 }, // Shadow Master
        { 562, 400 }, // Dark Mammoth
        { 563, 356 }, // Dark Giant
        { 564, 378 }, // Dark Coolutin
        { 565, 400 }, // Dark Iron Knight
        { 569, 194 }, // Venomous Chain Scorpion
        { 570, 198 }, // Bone Scorpion
        { 571, 204 }, // Orcus
        { 572, 292 }, // Gollock
        { 573, 206 }, // Crypta
        { 574, 219 }, // Crypos
        { 575, 309 }, // Condra
        { 576, 320 }, // Narcondra
        { 700, 52 }, // Kundun 1
        { 701, 90 }, // Kundun 2
        { 702, 130 }, // Kundun 3
        { 703, 160 }, // Kundun 4
        { 704, 220 }, // Kundun 5
        { 705, 320 }, // Kundun 6
        { 706, 371 }, // Kundun 7
    };

    // The level of the monster on the server; 0 if unknown.
    inline int GetMonsterLevel(const int number)
    {
        for (const auto& entry : MonsterLevels)
        {
            if (entry.Number == number)
            {
                return entry.Level;
            }
        }

        return 0;
    }
}
