#pragma once

// Generated by tools/balance/skill_cast_time.py - do not edit by hand.
// Skill fix time (session 12): the client can't cast a skill faster than its animation at attack speed 335 /
// magic speed 285 (10 000 agility + a median weapon), not below 0.15 s; harmony options 11, 12, 13 of the
// rank 7-8 weapons lower the fix time of 3 skills of the class. Below and above the fix one speed curve
// (SkillCastTimeOptions.h, offsets 181 / 145). Must match the server plugin "Skill cast time"
// (SkillCastTimePlugIn / SkillCastTimeConfiguration) and the harmony options "Harmony Skill Fix Options".

namespace GameLogic::Combat::SkillCastTime
{
    inline constexpr float AttackSpeedAtFix = 335.0f;
    inline constexpr float MagicSpeedAtFix = 285.0f;
    inline constexpr float FixFloorSeconds = 0.15f;
    inline constexpr float CastFloorSeconds = 0.12f;
    inline constexpr float ElfOptionFactor = 0.6f;
    inline constexpr int OptionNumbers[3] = { 11, 12, 13 };
    // the share by which the option lowers the fix time, by harmony level 1..10 (0: no option)
    inline constexpr float OptionCut[11] = { 0.0f, 0.05f, 0.0722f, 0.0944f, 0.1167f, 0.1389f, 0.1611f, 0.1833f, 0.2056f, 0.2278f, 0.25f };
    inline constexpr int MaxOptionLevel = 10;
    inline constexpr int RequiredItemLevel = 10; // the Jewel of Harmony needs a weapon of +10
    // chance in percent to reach the level with a refine stone (server RefineStoneUpgradeConsumeHandlerPlugIn)
    inline constexpr int RefineChance[11] = { 0, 0, 100, 100, 70, 60, 50, 40, 30, 20, 10 };

    struct WeaponSkills
    {
        int Group;
        int Number;
        int ClassFamily; // number of the 1st class (0 DW, 4 DK, 8 elf, 12 MG, 16 DL, 20 SUM, 24 RF), -1 any
        int Skills[3];   // skills of the harmony options 11, 12, 13
    };

    inline constexpr WeaponSkills Weapons[] =
    {
        { 0, 17, -1, { 41, 43, 232 } }, // Dark Breaker: Twisting Slash, Death Stab, Strike of Destruction
        { 0, 20, -1, { 41, 43, 232 } }, // Knight Blade: Twisting Slash, Death Stab, Strike of Destruction
        { 0, 22, -1, { 41, 43, 232 } }, // Bone Blade: Twisting Slash, Death Stab, Strike of Destruction
        { 0, 24, -1, { 41, 43, 232 } }, // Daybreak: Twisting Slash, Death Stab, Strike of Destruction
        { 0, 18, -1, { 56, 41, 55 } }, // Thunder Blade: Power Slash, Twisting Slash, Fire Slash
        { 0, 21, -1, { 56, 41, 55 } }, // Dark Reign Blade: Power Slash, Twisting Slash, Fire Slash
        { 0, 23, -1, { 56, 41, 55 } }, // Explosion Blade: Power Slash, Twisting Slash, Fire Slash
        { 0, 25, -1, { 56, 41, 55 } }, // Sword Dancer: Power Slash, Twisting Slash, Fire Slash
        { 0, 31, -1, { 9, 237, 8 } }, // Rune Blade: Evil Spirit, Gigantic Storm, Twister
        { 5, 11, 12, { 9, 237, 8 } }, // Staff of Kundun: Evil Spirit, Gigantic Storm, Twister
        { 5, 11, 0, { 9, 38, 39 } }, // Staff of Kundun: Evil Spirit, Decay, Ice Storm
        { 5, 9, -1, { 9, 38, 39 } }, // Dragon Soul Staff: Evil Spirit, Decay, Ice Storm
        { 5, 12, -1, { 9, 38, 39 } }, // Grand Viper Staff: Evil Spirit, Decay, Ice Storm
        { 5, 13, -1, { 9, 38, 39 } }, // Platina Staff: Evil Spirit, Decay, Ice Storm
        { 4, 19, -1, { 235, 52, 46 } }, // Great Reign Crossbow: Multi-Shot, Penetration, Starfall
        { 4, 20, -1, { 235, 52, 46 } }, // Arrow Viper Bow: Multi-Shot, Penetration, Starfall
        { 4, 21, -1, { 235, 52, 46 } }, // Sylph Wind Bow: Multi-Shot, Penetration, Starfall
        { 4, 22, -1, { 235, 52, 46 } }, // Albatross Bow: Multi-Shot, Penetration, Starfall
        { 2, 12, -1, { 78, 61, 238 } }, // Great Lord Scepter: Fire Scream, Fire Burst, Chaotic Diseier
        { 2, 14, -1, { 78, 61, 238 } }, // Soleil Scepter: Fire Scream, Fire Burst, Chaotic Diseier
        { 2, 15, -1, { 78, 61, 238 } }, // Shining Scepter: Fire Scream, Fire Burst, Chaotic Diseier
        { 5, 19, -1, { 230, 215, 225 } }, // Storm Blitz Stick: Lightning Shock, Chain Lightning, Pollution
        { 5, 20, -1, { 230, 215, 225 } }, // Eternal Wing Stick: Lightning Shock, Chain Lightning, Pollution
        { 0, 34, -1, { 264, 263, 260 } }, // Piercing Blade Glove: Dragon Roar, Dark Side, Killing Blow
        { 0, 35, -1, { 264, 263, 260 } }, // Phoenix Soul Star: Dragon Roar, Dark Side, Killing Blow
    };

    // The stat an attack action follows (None: a fixed play speed).
    enum class SpeedStat
    {
        None,
        Attack,
        Magic,
    };

    struct SkillTime
    {
        int Skill;
        int FixMilliseconds; // the animation at the fix speed, not below the floor
        SpeedStat Speed;     // the speed the animation follows below and above the fix (None: always the fix time)
    };

    // the server: SkillCastTimeConfiguration.FixTimes and SpeedCurves (the tooltip shows the casts per second with it)
    inline constexpr SkillTime SkillTimes[] =
    {
        { 1, 279, SpeedStat::Magic }, // Poison
        { 2, 279, SpeedStat::Magic }, // Meteorite
        { 3, 279, SpeedStat::Magic }, // Lightning
        { 4, 279, SpeedStat::Magic }, // Fire Ball
        { 5, 279, SpeedStat::Magic }, // Flame
        { 7, 279, SpeedStat::Magic }, // Ice
        { 8, 279, SpeedStat::Magic }, // Twister
        { 9, 279, SpeedStat::Magic }, // Evil Spirit
        { 10, 673, SpeedStat::Magic }, // Hellfire
        { 11, 279, SpeedStat::Magic }, // Power Wave
        { 12, 536, SpeedStat::Magic }, // Aqua Beam
        { 13, 279, SpeedStat::Magic }, // Cometfall
        { 14, 444, SpeedStat::Magic }, // Inferno
        { 17, 279, SpeedStat::Magic }, // Energy Ball
        { 19, 195, SpeedStat::Attack }, // Falling Slash
        { 20, 171, SpeedStat::Attack }, // Lunge
        { 21, 174, SpeedStat::Attack }, // Uppercut
        { 22, 171, SpeedStat::Attack }, // Cyclone
        { 23, 177, SpeedStat::Attack }, // Slash
        { 24, 171, SpeedStat::Attack }, // Triple Shot
        { 38, 279, SpeedStat::Magic }, // Decay
        { 39, 279, SpeedStat::Magic }, // Ice Storm
        { 41, 329, SpeedStat::Attack }, // Twisting Slash
        { 42, 1158, SpeedStat::None }, // Rageful Blow
        { 43, 176, SpeedStat::Attack }, // Death Stab
        { 44, 195, SpeedStat::Attack }, // Crescent Moon Slash
        { 45, 279, SpeedStat::None }, // Lance
        { 46, 171, SpeedStat::Attack }, // Starfall
        { 47, 220, SpeedStat::Attack }, // Impale
        { 51, 171, SpeedStat::Attack }, // Ice Arrow
        { 52, 171, SpeedStat::Attack }, // Penetration
        { 55, 289, SpeedStat::None }, // Fire Slash
        { 56, 176, SpeedStat::Attack }, // Power Slash
        { 57, 253, SpeedStat::None }, // Spiral Slash
        { 60, 176, SpeedStat::Attack }, // Force
        { 61, 176, SpeedStat::Attack }, // Fire Burst
        { 62, 268, SpeedStat::Attack }, // Earthshake
        { 66, 176, SpeedStat::Attack }, // Force Wave
        { 73, 182, SpeedStat::None }, // Mana Rays
        { 74, 176, SpeedStat::Attack }, // Fire Blast
        { 78, 176, SpeedStat::Attack }, // Fire Scream
        { 214, 293, SpeedStat::Magic }, // Drain Life
        { 215, 244, SpeedStat::Magic }, // Chain Lightning
        { 223, 537, SpeedStat::Magic }, // Explosion
        { 224, 537, SpeedStat::Magic }, // Requiem
        { 225, 537, SpeedStat::Magic }, // Pollution
        { 230, 478, SpeedStat::Magic }, // Lightning Shock
        { 232, 268, SpeedStat::Attack }, // Strike of Destruction
        { 235, 171, SpeedStat::Attack }, // Multi-Shot
        { 236, 444, SpeedStat::Magic }, // Flame Strike
        { 237, 308, SpeedStat::Magic }, // Gigantic Storm
        { 238, 176, SpeedStat::Attack }, // Chaotic Diseier
        { 260, 449, SpeedStat::Attack }, // Killing Blow
        { 263, 536, SpeedStat::Attack }, // Dark Side
        { 264, 412, SpeedStat::Attack }, // Dragon Roar
        { 269, 171, SpeedStat::None }, // Charge
    };
}
