#pragma once

// Generated by tools/balance/skill_cast_time.py - do not edit by hand.
// Skill fix time (session 12): the client can't cast a skill faster than its animation at attack speed 335 /
// magic speed 285 (10 000 agility + a median weapon), not below 0.15 s; harmony options 11, 12, 13 of the
// rank 7-8 weapons lower the fix time of 3 skills of the class. Must match the server plugin "Skill cast time"
// (SkillCastTimePlugIn / SkillCastTimeConfiguration) and the harmony options "Harmony Skill Fix Options".

namespace GameLogic::Combat::SkillCastTime
{
    inline constexpr float AttackSpeedAtFix = 335.0f;
    inline constexpr float MagicSpeedAtFix = 285.0f;
    inline constexpr float FixFloorSeconds = 0.15f;
    inline constexpr float CastFloorSeconds = 0.12f;
    inline constexpr float ElfOptionFactor = 0.6f;
    inline constexpr int OptionNumbers[3] = { 11, 12, 13 };
    // the share by which the option lowers the fix time, by harmony level 0..13
    inline constexpr float OptionCut[14] = { 0.05f, 0.0654f, 0.0808f, 0.0962f, 0.1115f, 0.1269f, 0.1423f, 0.1577f, 0.1731f, 0.1885f, 0.2038f, 0.2192f, 0.2346f, 0.25f };

    struct WeaponSkills
    {
        int Group;
        int Number;
        int ClassFamily; // number of the 1st class (0 DW, 4 DK, 8 elf, 12 MG, 16 DL, 20 SUM, 24 RF), -1 any
        int Skills[3];   // skills of the harmony options 11, 12, 13
    };

    inline constexpr WeaponSkills Weapons[] =
    {
        { 0, 17, -1, { 41, 43, 232 } }, // Dark Breaker: Twisting Slash, Death Stab, Strike of Destruction
        { 0, 20, -1, { 41, 43, 232 } }, // Knight Blade: Twisting Slash, Death Stab, Strike of Destruction
        { 0, 22, -1, { 41, 43, 232 } }, // Bone Blade: Twisting Slash, Death Stab, Strike of Destruction
        { 0, 24, -1, { 41, 43, 232 } }, // Daybreak: Twisting Slash, Death Stab, Strike of Destruction
        { 0, 18, -1, { 56, 41, 55 } }, // Thunder Blade: Power Slash, Twisting Slash, Fire Slash
        { 0, 21, -1, { 56, 41, 55 } }, // Dark Reign Blade: Power Slash, Twisting Slash, Fire Slash
        { 0, 23, -1, { 56, 41, 55 } }, // Explosion Blade: Power Slash, Twisting Slash, Fire Slash
        { 0, 25, -1, { 56, 41, 55 } }, // Sword Dancer: Power Slash, Twisting Slash, Fire Slash
        { 0, 31, -1, { 9, 237, 8 } }, // Rune Blade: Evil Spirit, Gigantic Storm, Twister
        { 5, 11, 12, { 9, 237, 8 } }, // Staff of Kundun: Evil Spirit, Gigantic Storm, Twister
        { 5, 11, 0, { 9, 38, 39 } }, // Staff of Kundun: Evil Spirit, Decay, Ice Storm
        { 5, 9, -1, { 9, 38, 39 } }, // Dragon Soul Staff: Evil Spirit, Decay, Ice Storm
        { 5, 12, -1, { 9, 38, 39 } }, // Grand Viper Staff: Evil Spirit, Decay, Ice Storm
        { 5, 13, -1, { 9, 38, 39 } }, // Platina Staff: Evil Spirit, Decay, Ice Storm
        { 4, 19, -1, { 235, 52, 46 } }, // Great Reign Crossbow: Multi-Shot, Penetration, Starfall
        { 4, 20, -1, { 235, 52, 46 } }, // Arrow Viper Bow: Multi-Shot, Penetration, Starfall
        { 4, 21, -1, { 235, 52, 46 } }, // Sylph Wind Bow: Multi-Shot, Penetration, Starfall
        { 4, 22, -1, { 235, 52, 46 } }, // Albatross Bow: Multi-Shot, Penetration, Starfall
        { 2, 12, -1, { 78, 61, 238 } }, // Great Lord Scepter: Fire Scream, Fire Burst, Chaotic Diseier
        { 2, 14, -1, { 78, 61, 238 } }, // Soleil Scepter: Fire Scream, Fire Burst, Chaotic Diseier
        { 2, 15, -1, { 78, 61, 238 } }, // Shining Scepter: Fire Scream, Fire Burst, Chaotic Diseier
        { 5, 19, -1, { 230, 215, 225 } }, // Storm Blitz Stick: Lightning Shock, Chain Lightning, Pollution
        { 5, 20, -1, { 230, 215, 225 } }, // Eternal Wing Stick: Lightning Shock, Chain Lightning, Pollution
        { 0, 34, -1, { 264, 263, 260 } }, // Piercing Blade Glove: Dragon Roar, Dark Side, Killing Blow
        { 0, 35, -1, { 264, 263, 260 } }, // Phoenix Soul Star: Dragon Roar, Dark Side, Killing Blow
    };
}
