#pragma once

#include <cmath>

namespace GameLogic::Items
{
    // Armor defense by set rank. Must match the server data (class-balance.sql, generated by
    // tools/balance/class_balance_sql.py): the base defense of every armor piece and its level bonus.
    // 1:1 defense (Final Defense = Base Defense): the set number x the armor of the class owning the set.
    // Level bonus = base x (4% per level up to +9, then 6/6/8/8/10/10%) x (1 + 3% x (rank - 1)),
    // rounded half up — the server stores the same rounded values per level.
    struct ArmorRank
    {
        int Type;
        int BaseDefense;
        int Rank;
    };

    // generated:class-armor:start
    // Armor of the class (class_balance.ARMOR): shields count x this for the class (server: Shield Defense (item) -> Base Defense).
    inline constexpr float ClassArmor[] = { 0.30f, 0.41f, 0.40f, 0.44f, 0.57f, 0.35f, 0.47f }; // by CLASS_* base class
    // generated:class-armor:end

    inline constexpr ArmorRank ArmorRanks[] =
    {
        { ITEM_HELM + 2, 12, 1 }, // Pad Helm
        { ITEM_ARMOR + 2, 17, 1 }, // Pad Armor
        { ITEM_PANTS + 2, 14, 1 }, // Pad Pants
        { ITEM_GLOVES + 2, 10, 1 }, // Pad Gloves
        { ITEM_BOOTS + 2, 12, 1 }, // Pad Boots
        { ITEM_HELM + 5, 16, 1 }, // Leather Helm
        { ITEM_ARMOR + 5, 23, 1 }, // Leather Armor
        { ITEM_PANTS + 5, 20, 1 }, // Leather Pants
        { ITEM_GLOVES + 5, 14, 1 }, // Leather Gloves
        { ITEM_BOOTS + 5, 16, 1 }, // Leather Boots
        { ITEM_HELM + 10, 16, 1 }, // Vine Helm
        { ITEM_ARMOR + 10, 22, 1 }, // Vine Armor
        { ITEM_PANTS + 10, 19, 1 }, // Vine Pants
        { ITEM_GLOVES + 10, 14, 1 }, // Vine Gloves
        { ITEM_BOOTS + 10, 16, 1 }, // Vine Boots
        { ITEM_HELM + 39, 16, 1 }, // Mistery Helm
        { ITEM_ARMOR + 39, 23, 1 }, // Mistery Armor
        { ITEM_PANTS + 39, 19, 1 }, // Mistery Pants
        { ITEM_GLOVES + 39, 14, 1 }, // Mistery Gloves
        { ITEM_BOOTS + 39, 16, 1 }, // Mistery Boots
        { ITEM_HELM + 4, 28, 2 }, // Bone Helm
        { ITEM_ARMOR + 4, 40, 2 }, // Bone Armor
        { ITEM_PANTS + 4, 34, 2 }, // Bone Pants
        { ITEM_GLOVES + 4, 25, 2 }, // Bone Gloves
        { ITEM_BOOTS + 4, 28, 2 }, // Bone Boots
        { ITEM_HELM + 6, 38, 2 }, // Scale Helm
        { ITEM_ARMOR + 6, 55, 2 }, // Scale Armor
        { ITEM_PANTS + 6, 47, 2 }, // Scale Pants
        { ITEM_GLOVES + 6, 34, 2 }, // Scale Gloves
        { ITEM_BOOTS + 6, 38, 2 }, // Scale Boots
        { ITEM_HELM + 11, 37, 2 }, // Silk Helm
        { ITEM_ARMOR + 11, 54, 2 }, // Silk Armor
        { ITEM_PANTS + 11, 46, 2 }, // Silk Pants
        { ITEM_GLOVES + 11, 33, 2 }, // Silk Gloves
        { ITEM_BOOTS + 11, 37, 2 }, // Silk Boots
        { ITEM_HELM + 7, 37, 3 }, // Sphinx Mask
        { ITEM_ARMOR + 7, 53, 3 }, // Sphinx Armor
        { ITEM_PANTS + 7, 45, 3 }, // Sphinx Pants
        { ITEM_GLOVES + 7, 33, 3 }, // Sphinx Gloves
        { ITEM_BOOTS + 7, 37, 3 }, // Sphinx Boots
        { ITEM_HELM + 8, 50, 3 }, // Brass Helm
        { ITEM_ARMOR + 8, 73, 3 }, // Brass Armor
        { ITEM_PANTS + 8, 61, 3 }, // Brass Pants
        { ITEM_GLOVES + 8, 45, 3 }, // Brass Gloves
        { ITEM_BOOTS + 8, 50, 3 }, // Brass Boots
        { ITEM_HELM + 12, 49, 3 }, // Wind Helm
        { ITEM_ARMOR + 12, 71, 3 }, // Wind Armor
        { ITEM_PANTS + 12, 60, 3 }, // Wind Pants
        { ITEM_GLOVES + 12, 44, 3 }, // Wind Gloves
        { ITEM_BOOTS + 12, 49, 3 }, // Wind Boots
        { ITEM_HELM + 3, 52, 4 }, // Legendary Helm
        { ITEM_ARMOR + 3, 76, 4 }, // Legendary Armor
        { ITEM_PANTS + 3, 64, 4 }, // Legendary Pants
        { ITEM_GLOVES + 3, 46, 4 }, // Legendary Gloves
        { ITEM_BOOTS + 3, 52, 4 }, // Legendary Boots
        { ITEM_HELM + 9, 72, 4 }, // Plate Helm
        { ITEM_ARMOR + 9, 103, 4 }, // Plate Armor
        { ITEM_PANTS + 9, 87, 4 }, // Plate Pants
        { ITEM_GLOVES + 9, 64, 4 }, // Plate Gloves
        { ITEM_BOOTS + 9, 72, 4 }, // Plate Boots
        { ITEM_HELM + 13, 70, 4 }, // Spirit Helm
        { ITEM_ARMOR + 13, 101, 4 }, // Spirit Armor
        { ITEM_PANTS + 13, 85, 4 }, // Spirit Pants
        { ITEM_GLOVES + 13, 62, 4 }, // Spirit Gloves
        { ITEM_BOOTS + 13, 70, 4 }, // Spirit Boots
        { ITEM_HELM + 25, 100, 4 }, // Light Plate Mask
        { ITEM_ARMOR + 25, 144, 4 }, // Light Plate Armor
        { ITEM_PANTS + 25, 121, 4 }, // Light Plate Pants
        { ITEM_GLOVES + 25, 88, 4 }, // Light Plate Gloves
        { ITEM_BOOTS + 25, 100, 4 }, // Light Plate Boots
        { ITEM_HELM + 40, 61, 4 }, // Red Wing Helm
        { ITEM_ARMOR + 40, 88, 4 }, // Red Wing Armor
        { ITEM_PANTS + 40, 75, 4 }, // Red Wing Pants
        { ITEM_GLOVES + 40, 54, 4 }, // Red Wing Gloves
        { ITEM_BOOTS + 40, 61, 4 }, // Red Wing Boots
        { ITEM_HELM + 35, 77, 5 }, // Eclipse Helm
        { ITEM_ARMOR + 35, 112, 5 }, // Eclipse Armor
        { ITEM_PANTS + 35, 95, 5 }, // Eclipse Pants
        { ITEM_GLOVES + 35, 69, 5 }, // Eclipse Gloves
        { ITEM_BOOTS + 35, 77, 5 }, // Eclipse Boots
        { ITEM_HELM + 1, 95, 5 }, // Dragon Helm
        { ITEM_ARMOR + 1, 138, 5 }, // Dragon Armor
        { ITEM_PANTS + 1, 116, 5 }, // Dragon Pants
        { ITEM_GLOVES + 1, 85, 5 }, // Dragon Gloves
        { ITEM_BOOTS + 1, 95, 5 }, // Dragon Boots
        { ITEM_HELM + 34, 116, 5 }, // Ashcrow Helm
        { ITEM_ARMOR + 34, 168, 5 }, // Ashcrow Armor
        { ITEM_PANTS + 34, 142, 5 }, // Ashcrow Pants
        { ITEM_GLOVES + 34, 103, 5 }, // Ashcrow Gloves
        { ITEM_BOOTS + 34, 116, 5 }, // Ashcrow Boots
        { ITEM_HELM + 14, 93, 5 }, // Guardian Helm
        { ITEM_ARMOR + 14, 134, 5 }, // Guardian Armor
        { ITEM_PANTS + 14, 114, 5 }, // Guardian Pants
        { ITEM_GLOVES + 14, 83, 5 }, // Guardian Gloves
        { ITEM_BOOTS + 14, 93, 5 }, // Guardian Boots
        { ITEM_HELM + 36, 114, 5 }, // Iris Helm
        { ITEM_ARMOR + 36, 164, 5 }, // Iris Armor
        { ITEM_PANTS + 36, 139, 5 }, // Iris Pants
        { ITEM_GLOVES + 36, 101, 5 }, // Iris Gloves
        { ITEM_BOOTS + 36, 114, 5 }, // Iris Boots
        { ITEM_HELM + 26, 147, 5 }, // Adamantine Mask
        { ITEM_ARMOR + 26, 213, 5 }, // Adamantine Armor
        { ITEM_PANTS + 26, 180, 5 }, // Adamantine Pants
        { ITEM_GLOVES + 26, 131, 5 }, // Adamantine Gloves
        { ITEM_BOOTS + 26, 147, 5 }, // Adamantine Boots
        { ITEM_HELM + 41, 90, 5 }, // Ancient Helm
        { ITEM_ARMOR + 41, 131, 5 }, // Ancient Armor
        { ITEM_PANTS + 41, 111, 5 }, // Ancient Pants
        { ITEM_GLOVES + 41, 80, 5 }, // Ancient Gloves
        { ITEM_BOOTS + 41, 90, 5 }, // Ancient Boots
        { ITEM_HELM + 59, 144, 5 }, // Sacred Helm
        { ITEM_ARMOR + 59, 209, 5 }, // Sacred Armor
        { ITEM_PANTS + 59, 177, 5 }, // Sacred Pants
        { ITEM_BOOTS + 59, 144, 5 }, // Sacred Boots
        { ITEM_HELM + 18, 116, 6 }, // Grand Soul Helm
        { ITEM_ARMOR + 18, 167, 6 }, // Grand Soul Armor
        { ITEM_PANTS + 18, 141, 6 }, // Grand Soul Pants
        { ITEM_GLOVES + 18, 103, 6 }, // Grand Soul Gloves
        { ITEM_BOOTS + 18, 116, 6 }, // Grand Soul Boots
        { ITEM_HELM + 16, 158, 6 }, // Black Dragon Helm
        { ITEM_ARMOR + 16, 228, 6 }, // Black Dragon Armor
        { ITEM_PANTS + 16, 193, 6 }, // Black Dragon Pants
        { ITEM_GLOVES + 16, 141, 6 }, // Black Dragon Gloves
        { ITEM_BOOTS + 16, 158, 6 }, // Black Dragon Boots
        { ITEM_HELM + 19, 154, 6 }, // Divine Helm
        { ITEM_ARMOR + 19, 223, 6 }, // Divine Armor
        { ITEM_PANTS + 19, 188, 6 }, // Divine Pants
        { ITEM_GLOVES + 19, 137, 6 }, // Divine Gloves
        { ITEM_BOOTS + 19, 154, 6 }, // Divine Boots
        { ITEM_ARMOR + 15, 299, 6 }, // Storm Crow Armor
        { ITEM_PANTS + 15, 253, 6 }, // Storm Crow Pants
        { ITEM_GLOVES + 15, 184, 6 }, // Storm Crow Gloves
        { ITEM_BOOTS + 15, 207, 6 }, // Storm Crow Boots
        { ITEM_HELM + 27, 220, 6 }, // Dark Steel Mask
        { ITEM_ARMOR + 27, 317, 6 }, // Dark Steel Armor
        { ITEM_PANTS + 27, 268, 6 }, // Dark Steel Pants
        { ITEM_GLOVES + 27, 196, 6 }, // Dark Steel Gloves
        { ITEM_BOOTS + 27, 220, 6 }, // Dark Steel Boots
        { ITEM_HELM + 42, 135, 6 }, // Black Rose Helm
        { ITEM_ARMOR + 42, 195, 6 }, // Black Rose Armor
        { ITEM_PANTS + 42, 165, 6 }, // Black Rose Pants
        { ITEM_GLOVES + 42, 120, 6 }, // Black Rose Gloves
        { ITEM_BOOTS + 42, 135, 6 }, // Black Rose Boots
        { ITEM_HELM + 60, 216, 6 }, // Storm Hard Helm
        { ITEM_ARMOR + 60, 312, 6 }, // Storm Hard Armor
        { ITEM_PANTS + 60, 264, 6 }, // Storm Hard Pants
        { ITEM_BOOTS + 60, 216, 6 }, // Storm Hard Boots
        { ITEM_HELM + 22, 162, 7 }, // Dark Soul Helm
        { ITEM_ARMOR + 22, 233, 7 }, // Dark Soul Armor
        { ITEM_PANTS + 22, 197, 7 }, // Dark Soul Pants
        { ITEM_GLOVES + 22, 144, 7 }, // Dark Soul Gloves
        { ITEM_BOOTS + 22, 162, 7 }, // Dark Soul Boots
        { ITEM_HELM + 17, 199, 7 }, // Dark Phoenix Helm
        { ITEM_ARMOR + 17, 287, 7 }, // Dark Phoenix Armor
        { ITEM_PANTS + 17, 243, 7 }, // Dark Phoenix Pants
        { ITEM_GLOVES + 17, 177, 7 }, // Dark Phoenix Gloves
        { ITEM_BOOTS + 17, 199, 7 }, // Dark Phoenix Boots
        { ITEM_HELM + 21, 243, 7 }, // Great Dragon Helm
        { ITEM_ARMOR + 21, 351, 7 }, // Great Dragon Armor
        { ITEM_PANTS + 21, 297, 7 }, // Great Dragon Pants
        { ITEM_GLOVES + 21, 216, 7 }, // Great Dragon Gloves
        { ITEM_BOOTS + 21, 243, 7 }, // Great Dragon Boots
        { ITEM_HELM + 24, 216, 7 }, // Red Spirit Helm
        { ITEM_ARMOR + 24, 311, 7 }, // Red Sprit Armor
        { ITEM_PANTS + 24, 263, 7 }, // Red Spirit Pants
        { ITEM_GLOVES + 24, 192, 7 }, // Red Spirit Gloves
        { ITEM_BOOTS + 24, 216, 7 }, // Red Spirit Boots
        { ITEM_ARMOR + 37, 376, 7 }, // Valiant Armor
        { ITEM_PANTS + 37, 318, 7 }, // Valiant Pants
        { ITEM_GLOVES + 37, 231, 7 }, // Valiant Gloves
        { ITEM_BOOTS + 37, 260, 7 }, // Valiant Boots
        { ITEM_ARMOR + 20, 418, 7 }, // Thunder Hawk Armor
        { ITEM_PANTS + 20, 353, 7 }, // Thunder Hawk Pants
        { ITEM_GLOVES + 20, 257, 7 }, // Thunder Hawk Gloves
        { ITEM_BOOTS + 20, 289, 7 }, // Thunder Hawk Boots
        { ITEM_ARMOR + 23, 459, 7 }, // Hurricane Armor
        { ITEM_PANTS + 23, 389, 7 }, // Hurricane Pants
        { ITEM_GLOVES + 23, 282, 7 }, // Hurricane Gloves
        { ITEM_BOOTS + 23, 318, 7 }, // Hurricane Boots
        { ITEM_HELM + 38, 276, 7 }, // Glorious Mask
        { ITEM_ARMOR + 38, 399, 7 }, // Glorious Armor
        { ITEM_PANTS + 38, 338, 7 }, // Glorious Pants
        { ITEM_GLOVES + 38, 246, 7 }, // Glorious Gloves
        { ITEM_BOOTS + 38, 276, 7 }, // Glorious Boots
        { ITEM_HELM + 28, 338, 7 }, // Dark Master Mask
        { ITEM_ARMOR + 28, 488, 7 }, // Dark Master Armor
        { ITEM_PANTS + 28, 413, 7 }, // Dark Master Pants
        { ITEM_GLOVES + 28, 300, 7 }, // Dark Master Gloves
        { ITEM_BOOTS + 28, 338, 7 }, // Dark Master Boots
        { ITEM_HELM + 44, 189, 7 }, // Lilium Helm
        { ITEM_ARMOR + 44, 272, 7 }, // Lilium Armor
        { ITEM_PANTS + 44, 230, 7 }, // Lilium Pants
        { ITEM_GLOVES + 44, 168, 7 }, // Lilium Gloves
        { ITEM_BOOTS + 44, 189, 7 }, // Lilium Boots
        { ITEM_HELM + 61, 301, 7 }, // Piercing Helm
        { ITEM_ARMOR + 61, 435, 7 }, // Piercing Armor
        { ITEM_PANTS + 61, 368, 7 }, // Piercing Pants
        { ITEM_BOOTS + 61, 301, 7 }, // Piercing Boots
        { ITEM_HELM + 30, 227, 8 }, // Venom Mist Helm
        { ITEM_ARMOR + 30, 328, 8 }, // Venom Mist Armor
        { ITEM_PANTS + 30, 277, 8 }, // Venom Mist Pants
        { ITEM_GLOVES + 30, 202, 8 }, // Venom Mist Gloves
        { ITEM_BOOTS + 30, 227, 8 }, // Venom Mist Boots
        { ITEM_HELM + 29, 310, 8 }, // Dragon Knight Helm
        { ITEM_ARMOR + 29, 448, 8 }, // Dragon Knight Armor
        { ITEM_PANTS + 29, 379, 8 }, // Dragon Knight Pants
        { ITEM_GLOVES + 29, 276, 8 }, // Dragon Knight Gloves
        { ITEM_BOOTS + 29, 310, 8 }, // Dragon Knight Boots
        { ITEM_HELM + 31, 302, 8 }, // Sylphid Ray Helm
        { ITEM_ARMOR + 31, 437, 8 }, // Sylphid Ray Armor
        { ITEM_PANTS + 31, 370, 8 }, // Sylphid Ray Pants
        { ITEM_GLOVES + 31, 269, 8 }, // Sylphid Ray Gloves
        { ITEM_BOOTS + 31, 302, 8 }, // Sylphid Ray Boots
        { ITEM_ARMOR + 32, 586, 8 }, // Volcano Armor
        { ITEM_PANTS + 32, 496, 8 }, // Volcano Pants
        { ITEM_GLOVES + 32, 361, 8 }, // Volcano Gloves
        { ITEM_BOOTS + 32, 406, 8 }, // Volcano Boots
        { ITEM_HELM + 33, 431, 8 }, // Sunlight Mask
        { ITEM_ARMOR + 33, 622, 8 }, // Sunlight Armor
        { ITEM_PANTS + 33, 527, 8 }, // Sunlight Pants
        { ITEM_GLOVES + 33, 383, 8 }, // Sunlight Gloves
        { ITEM_BOOTS + 33, 431, 8 }, // Sunlight Boots
        { ITEM_HELM + 43, 265, 8 }, // Aura Helm
        { ITEM_ARMOR + 43, 382, 8 }, // Aura Armor
        { ITEM_PANTS + 43, 323, 8 }, // Aura Pants
        { ITEM_GLOVES + 43, 235, 8 }, // Aura Gloves
        { ITEM_BOOTS + 43, 265, 8 }, // Aura Boots
        { ITEM_HELM + 73, 423, 8 }, // Phoenix Soul Helmet
        { ITEM_ARMOR + 73, 611, 8 }, // Phoenix Soul Armor
        { ITEM_PANTS + 73, 517, 8 }, // Phoenix Soul Pants
        { ITEM_BOOTS + 73, 423, 8 }, // Phoenix Soul Boots
    };

    inline const ArmorRank* FindArmorRank(const int itemType)
    {
        for (const auto& armor : ArmorRanks)
        {
            if (armor.Type == itemType)
            {
                return &armor;
            }
        }

        return nullptr;
    }

    inline int ArmorRankLevelBonus(const ArmorRank& armor, const int itemLevel)
    {
        static constexpr int CumulativePercent[16] = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 42, 48, 56, 64, 74, 84 };
        const int level = itemLevel < 0 ? 0 : (itemLevel > 15 ? 15 : itemLevel);
        const double bonus = armor.BaseDefense * CumulativePercent[level] / 100.0 * (1.0 + 0.03 * (armor.Rank - 1));
        return static_cast<int>(std::floor(bonus + 0.5));
    }
}
