#pragma once

#include <cmath>

namespace GameLogic::Items
{
    // Weapons by rank, generated by tools/balance/weapon_rebalance.py - the same numbers as the server
    // (Server/weapon-ranks.sql). Physical weapons: base damage and level bonus in % of the item damage
    // (0 = the weapon keeps its original damage, e.g. staffs); every weapon gives attack rate.
    struct WeaponRank
    {
        int Type;
        int DamageMin;
        int DamageMax;
        int Rank;
        int AttackRate;
    };

    inline constexpr WeaponRank WeaponRanks[] =
    {
        { ITEM_SWORD + 0, 0, 0, 1, 300 }, // Kris
        { ITEM_SWORD + 1, 0, 0, 1, 300 }, // Short Sword
        { ITEM_SWORD + 2, 0, 0, 1, 300 }, // Rapier
        { ITEM_SWORD + 3, 25, 40, 2, 340 }, // Katache
        { ITEM_SWORD + 4, 0, 0, 1, 300 }, // Sword of Assassin
        { ITEM_SWORD + 5, 68, 89, 3, 440 }, // Blade
        { ITEM_SWORD + 6, 27, 41, 2, 340 }, // Gladius
        { ITEM_SWORD + 7, 30, 43, 2, 340 }, // Falchion
        { ITEM_SWORD + 8, 57, 76, 3, 440 }, // Serpent Sword
        { ITEM_SWORD + 9, 91, 129, 3, 440 }, // Sword of Salamander
        { ITEM_SWORD + 10, 85, 111, 3, 440 }, // Light Saber
        { ITEM_SWORD + 11, 100, 129, 3, 440 }, // Legendary Sword
        { ITEM_SWORD + 12, 169, 227, 4, 560 }, // Heliacal Sword
        { ITEM_SWORD + 13, 136, 157, 4, 560 }, // Double Blade
        { ITEM_SWORD + 14, 149, 169, 4, 560 }, // Lighting Sword
        { ITEM_SWORD + 15, 146, 206, 4, 560 }, // Giant Sword
        { ITEM_SWORD + 16, 314, 344, 5, 790 }, // Sword of Destruction
        { ITEM_SWORD + 17, 834, 995, 7, 1340 }, // Dark Breaker
        { ITEM_SWORD + 18, 800, 960, 7, 1340 }, // Thunder Blade
        { ITEM_SWORD + 20, 923, 992, 8, 1580 }, // Knight Blade
        { ITEM_SWORD + 21, 964, 1191, 8, 1580 }, // Dark Reign Blade
        { ITEM_SWORD + 22, 1025, 1134, 8, 1580 }, // Bone Blade
        { ITEM_SWORD + 23, 1094, 1336, 8, 1580 }, // Explosion Blade
        { ITEM_SWORD + 24, 938, 1124, 7, 1340 }, // Daybreak
        { ITEM_SWORD + 25, 646, 805, 7, 1340 }, // Sword Dancer
        { ITEM_SWORD + 31, 572, 715, 7, 1340 }, // Rune Blade
        { ITEM_SWORD + 32, 199, 222, 5, 790 }, // Sacred Glove
        { ITEM_SWORD + 33, 443, 476, 6, 990 }, // Storm Hard Glove
        { ITEM_SWORD + 34, 543, 577, 7, 1340 }, // Piercing Blade Glove
        { ITEM_SWORD + 35, 780, 818, 8, 1580 }, // Phoenix Soul Star
        { ITEM_AXE + 0, 0, 0, 1, 300 }, // Small Axe
        { ITEM_AXE + 1, 0, 0, 1, 300 }, // Hand Axe
        { ITEM_AXE + 2, 0, 0, 1, 300 }, // Double Axe
        { ITEM_AXE + 3, 26, 39, 2, 340 }, // Tomahawk
        { ITEM_AXE + 4, 36, 52, 2, 340 }, // Elven Axe
        { ITEM_AXE + 5, 82, 100, 3, 440 }, // Battle Axe
        { ITEM_AXE + 6, 80, 106, 3, 440 }, // Nikkea Axe
        { ITEM_AXE + 7, 106, 132, 3, 440 }, // Larkan Axe
        { ITEM_AXE + 8, 163, 211, 4, 560 }, // Crescent Axe
        { ITEM_MACE + 0, 0, 0, 1, 300 }, // Mace
        { ITEM_MACE + 1, 0, 0, 1, 300 }, // Morning Star
        { ITEM_MACE + 2, 29, 43, 2, 340 }, // Flail
        { ITEM_MACE + 3, 85, 106, 3, 440 }, // Great Hammer
        { ITEM_MACE + 4, 298, 409, 5, 790 }, // Crystal Morning Star
        { ITEM_MACE + 5, 340, 459, 5, 790 }, // Crystal Sword
        { ITEM_MACE + 6, 109, 139, 3, 440 }, // Chaos Dragon Axe
        { ITEM_MACE + 7, 335, 432, 6, 990 }, // Elemental Mace
        { ITEM_MACE + 8, 97, 123, 4, 560 }, // Battle Scepter
        { ITEM_MACE + 9, 233, 278, 5, 790 }, // Master Scepter
        { ITEM_MACE + 10, 268, 308, 5, 790 }, // Great Scepter
        { ITEM_MACE + 11, 492, 551, 6, 990 }, // Lord Scepter
        { ITEM_MACE + 12, 968, 1076, 8, 1580 }, // Great Lord Scepter
        { ITEM_MACE + 14, 1058, 1246, 8, 1580 }, // Soleil Scepter
        { ITEM_MACE + 15, 566, 634, 7, 1340 }, // Shining Scepter
        { ITEM_SPEAR + 0, 89, 111, 3, 440 }, // Light Spear
        { ITEM_SPEAR + 1, 41, 56, 2, 340 }, // Spear
        { ITEM_SPEAR + 2, 0, 0, 1, 300 }, // Dragon Lance
        { ITEM_SPEAR + 3, 46, 57, 2, 340 }, // Giant Trident
        { ITEM_SPEAR + 4, 86, 119, 3, 440 }, // Serpent Spear
        { ITEM_SPEAR + 5, 0, 0, 1, 300 }, // Double Poleaxe
        { ITEM_SPEAR + 6, 38, 53, 2, 340 }, // Halberd
        { ITEM_SPEAR + 7, 84, 107, 3, 440 }, // Berdysh
        { ITEM_SPEAR + 8, 160, 207, 4, 560 }, // Great Scythe
        { ITEM_SPEAR + 9, 170, 227, 4, 560 }, // Bill of Balrog
        { ITEM_SPEAR + 10, 605, 757, 6, 990 }, // Dragon Spear
        { ITEM_BOW + 0, 0, 0, 1, 300 }, // Short Bow
        { ITEM_BOW + 1, 0, 0, 1, 300 }, // Bow
        { ITEM_BOW + 2, 27, 39, 2, 340 }, // Elven Bow
        { ITEM_BOW + 3, 32, 43, 2, 340 }, // Battle Bow
        { ITEM_BOW + 4, 76, 93, 3, 440 }, // Tiger Bow
        { ITEM_BOW + 5, 137, 165, 4, 560 }, // Silver Bow
        { ITEM_BOW + 6, 81, 98, 3, 440 }, // Chaos Nature Bow
        { ITEM_BOW + 8, 0, 0, 1, 300 }, // Crossbow
        { ITEM_BOW + 9, 0, 0, 1, 300 }, // Golden Crossbow
        { ITEM_BOW + 10, 30, 41, 2, 340 }, // Arquebus
        { ITEM_BOW + 11, 70, 88, 3, 440 }, // Light Crossbow
        { ITEM_BOW + 12, 121, 147, 4, 560 }, // Serpent Crossbow
        { ITEM_BOW + 13, 261, 315, 5, 790 }, // Bluewing Crossbow
        { ITEM_BOW + 14, 297, 351, 5, 790 }, // Aquagold Crossbow
        { ITEM_BOW + 16, 578, 720, 6, 990 }, // Saint Crossbow
        { ITEM_BOW + 17, 659, 805, 6, 990 }, // Celestial Bow
        { ITEM_BOW + 19, 818, 939, 7, 1340 }, // Great Reign Crossbow
        { ITEM_BOW + 20, 1367, 1564, 8, 1580 }, // Arrow Viper Bow
        { ITEM_BOW + 21, 1552, 1753, 8, 1580 }, // Sylph Wind Bow
        { ITEM_BOW + 22, 925, 1056, 7, 1340 }, // Albatross Bow
        { ITEM_STAFF + 0, 0, 0, 1, 300 }, // Skull Staff
        { ITEM_STAFF + 1, 0, 0, 2, 340 }, // Angelic Staff
        { ITEM_STAFF + 2, 0, 0, 3, 440 }, // Serpent Staff
        { ITEM_STAFF + 3, 0, 0, 4, 560 }, // Thunder Staff
        { ITEM_STAFF + 4, 0, 0, 4, 560 }, // Gorgon Staff
        { ITEM_STAFF + 5, 0, 0, 5, 790 }, // Legendary Staff
        { ITEM_STAFF + 6, 0, 0, 5, 790 }, // Staff of Resurrection
        { ITEM_STAFF + 7, 0, 0, 3, 440 }, // Chaos Lightning Staff
        { ITEM_STAFF + 8, 0, 0, 6, 990 }, // Staff of Destruction
        { ITEM_STAFF + 9, 0, 0, 7, 1340 }, // Dragon Soul Staff
        { ITEM_STAFF + 11, 0, 0, 8, 1580 }, // Staff of Kundun
        { ITEM_STAFF + 12, 0, 0, 8, 1580 }, // Grand Viper Staff
        { ITEM_STAFF + 13, 0, 0, 7, 1340 }, // Platina Staff
        { ITEM_STAFF + 14, 0, 0, 1, 300 }, // Mistery Stick
        { ITEM_STAFF + 15, 0, 0, 2, 340 }, // Violent Wind Stick
        { ITEM_STAFF + 16, 0, 0, 4, 560 }, // Red Wing Stick
        { ITEM_STAFF + 17, 0, 0, 5, 790 }, // Ancient Stick
        { ITEM_STAFF + 18, 0, 0, 6, 990 }, // Demonic Stick
        { ITEM_STAFF + 19, 0, 0, 7, 1340 }, // Storm Blitz Stick
        { ITEM_STAFF + 20, 0, 0, 8, 1580 }, // Eternal Wing Stick
        { ITEM_STAFF + 21, 0, 0, 3, 440 }, // Book of Sahamutt
        { ITEM_STAFF + 22, 0, 0, 4, 560 }, // Book of Neil
        { ITEM_STAFF + 23, 0, 0, 5, 790 }, // Book of Lagle
    };

    inline const WeaponRank* FindWeaponRank(const int itemType)
    {
        for (const auto& weapon : WeaponRanks)
        {
            if (weapon.Type == itemType)
            {
                return &weapon;
            }
        }

        return nullptr;
    }

    inline int WeaponRankLevelBonus(const int baseDamage, const int rank, const int itemLevel)
    {
        static constexpr int CumulativePercent[16] = { 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 42, 48, 56, 64, 74, 84 };
        const int level = itemLevel < 0 ? 0 : (itemLevel > 15 ? 15 : itemLevel);
        return static_cast<int>(baseDamage * CumulativePercent[level] / 100.0 * (1.0 + 0.03 * (rank - 1)) + 0.5);
    }
}
